extends:
  - standard-with-typescript
overrides:
  - files: ['*.ts']
    rules:
      import/no-default-export: error
      newline-before-return: error
      padding-line-between-statements:
        - error
        - blankLine: always
          prev: [block-like, if]
          next: '*'
        - blankLine: always
          prev: '*'
          next: [block-like, if]
        - blankLine: always
          prev: [const, let]
          next: [expression, for]
        - blankLine: always
          prev: expression
          next: [const, let]
        - blankLine: always
          prev: [multiline-const, multiline-let]
          next: '*'
        - blankLine: always
          prev: '*'
          next: [multiline-const, multiline-let]
      function-paren-newline:
        - error
        - never
      max-len:
        - error
        - 100
      max-depth: [error, 2]
      max-statements-per-line:
        - error
        - max: 1
      curly: [error, multi]
      no-trailing-spaces: warn      # prevents IDE
      no-multiple-empty-lines: warn # from going crazy
      import/order:
        - error
        - groups:
            - builtin
            - external
            - internal
            - parent
            - index
            - sibling
            - object
            - type
      max-params: error
      arrow-parens: error
      no-warning-comments: error
      func-style:
        - error
        - declaration
      '@typescript-eslint/consistent-type-imports':
        - error
        - fixStyle: separate-type-imports
      '@typescript-eslint/member-ordering': error
      '@typescript-eslint/explicit-member-accessibility': error
      '@typescript-eslint/no-confusing-void-expression': off
      '@typescript-eslint/return-await': off
      '@typescript-eslint/no-dynamic-delete': off
      no-void: off
      eqeqeq:
        - error
        - always
        - null: always
      '@typescript-eslint/no-unsafe-argument': warn
      '@typescript-eslint/no-non-null-assertion': warn
      '@typescript-eslint/non-nullable-type-assertion-style': warn
      '@typescript-eslint/unbound-method': warn

  - files: ["*.test.ts", "**/test/**"]
    extends: 'plugin:@typescript-eslint/disable-type-checked'
    env:
      jest: true
  - files: ['**/features/**/*.ts']
    extends: 'plugin:@typescript-eslint/disable-type-checked'
    rules:
       '@typescript-eslint/prefer-nullish-coalescing': 'off'
       '@typescript-eslint/strict-boolean-expressions': 'off'
parserOptions:
  project: true
env:
  node: true
ignorePatterns:
  - '*.d.ts'
  - '*.js'
