version: "3.9"
services:
  verdaccio:
    image: verdaccio/verdaccio:5.10.2
    ports: ['4873:4873']
  rabbitmq:
    image: rabbitmq:3.10.0-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: developer
      RABBITMQ_DEFAULT_PASS: secret
  mongodb:
    image: mongo:5.0.8
    ports: ['27017:27017']
    environment:
      MONGO_INITDB_ROOT_USERNAME: developer
      MONGO_INITDB_ROOT_PASSWORD: secret
  mongos:
    image: 'bitnami/mongodb-sharded:latest'
    hostname: mongos
    environment:
      - MONGODB_SHARDING_MODE=mongos
      - MONGODB_CFG_PRIMARY_HOST=mongodb-cfg
      - MONGODB_CFG_REPLICA_SET_NAME=cfgreplicaset
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
  mongodb-shard0-primary:
    image: 'bitnami/mongodb-sharded:latest'
    environment:
      - MONGODB_SHARDING_MODE=shardsvr
      - MONGODB_MONGOS_HOST=mongos
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=shard0
  mongodb-configsvr-primary:
    image: 'bitnami/mongodb-sharded:latest'
    hostname: mongodb-cfg
    environment:
      - MONGODB_SHARDING_MODE=configsvr
      - MONGODB_ROOT_PASSWORD=password123
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=cfgreplicaset
  postgres:
    image: postgres:14.4
    ports: ['5432:5432']
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: integration
  redis0:
    image: redis:7.0.11
    ports:
      - '6379:6379'
  redis1:
    image: redis:7.0.11
    ports:
      - '6378:6379'
  redis2:
    image: redis:7.0.11
    ports:
      - '6377:6379'
  http-echo:
    image: ealen/echo-server:0.7.0
    ports: ['8888:80']
  localstack:
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566'
      - '127.0.0.1:4510-4559:4510-4559'
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=developer
      - AWS_SECRET_ACCESS_KEY=secret
