$schema: https://json-schema.org/draft/2019-09/schema

definitions:
  node:
    oneOf:
      - $ref: '#/definitions/locator'
      - type: object
        patternProperties:
          '.*':
            $ref: '#/definitions/node'
  locator:
    type: string

type: object
patternProperties:
  '.*':
    $ref: '#/definitions/node'
