{{- range .Values.compositions }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composition-{{ required "composition name is required" .name }}
spec:
  replicas: {{ .replicas | default 2 }}
  selector:
    matchLabels:
      toa.io/composition: {{ .name }}
  template:
    metadata:
      labels:
        toa.io/composition: {{ .name }}
        {{- range .components }}
        {{ . }}: "1"
        {{- end }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ .image }}
          {{- if $.Values.variables }}
          env:
            {{- range $component := .components }}
              {{- range $key, $vars := $.Values.variables }}
                {{- if eq $component $key }}
                  {{- range $vars }}
                  {{- include "env.var" . | indent 12 }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- range $.Values.variables.global }}
            {{- include "env.var" . | indent 12 }}
            {{- end }}
          {{- end }}
      {{- if $.Values.credentials }}
      imagePullSecrets:
        - name: {{ $.Values.credentials }}
      {{- end }}
---
{{- end }}
