{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: extension-{{ required "deployment name is required" .name }}
spec:
  replicas: {{ .replicas | default 2 }}
  selector:
    matchLabels:
      toa.io/service: extension-{{ .name }}
  template:
    metadata:
      labels:
        toa.io/service: extension-{{ .name }}
    spec:
      containers:
        - name: extension-{{ .name }}
          image: {{ .image }}
          {{- if .variables }}
          env:
            {{- range .variables }}
            {{- include "env.var" . | indent 12 }}
            {{- end }}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: extension-{{ .name }}
spec:
  type: ClusterIP
  selector:
    toa.io/service: extension-{{ .name }}
  ports:
    - name: port-{{ .port }}
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port }}
---
{{- if .ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: extension-{{ .name }}
  {{- if .ingress.annotations }}
  annotations:
{{ toYaml .ingress.annotations | indent 4 }}
  {{- end }}
spec:
  {{- if .ingress.class }}
  ingressClassName: {{ .ingress.class }}
  {{- end }}
  rules:
    - host: {{ required "ingress.host is required" .ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: extension-{{ .name }}
                port:
                  number: 8000
{{- end }}
{{- end }}
