name: Publish

on:
  pull_request:
    types: [closed]
    branches:
      - main
      - dev
      - fix/workflow

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16  # TODO: matrix

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          npm whoami
          
          if [ ${{ github.base_ref }} = main ]; then
            npx lerna publish --no-verify-access --conventional-graduate --yes
          else
            npx lerna publish --no-verify-access --conventional-prerelease --preid dev --no-changelog --yes
          fi
