name: Test

on:
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "package-lock.json"
      - ".github/workflows/pr.yaml"
    branches:
      - dev

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        env:
          HUSKY: 0

      - name: Check code style
        run: npx eslint .

      - name: Run unit tests
        run: npm run test:unit -- --testTimeout=30000 --reporters=github-actions --reporters=summary
