name: Release

on:
  pull_request:
    types: [closed]
    branches:
      - release
      - alpha

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: npm install
      - run: npm test

  publish:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.TOABOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.TOABOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOABOT_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.gpg.outputs.email }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          if [ ${{ github.base_ref }} = release ]; then
            npx lerna@7.3.0 publish --conventional-graduate --no-commit-hooks --no-changelog --yes --message "ci: %s" --sign-git-commit
          else
            npx lerna@7.3.0 publish --conventional-prerelease --preid alpha --no-commit-hooks --no-changelog --yes --message "ci: %s" --git-tag-command "echo %s" --sign-git-commit
          fi

          git fetch
          git checkout dev
          git merge ${{ github.base_ref }}
          git push --all origin --no-verify
