name: Version

on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: npm install
      - run: npm test

  version:
    if: github.event.pull_request.merged == true
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Import GPG key
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.TOABOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.TOABOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.TOABOT_GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.gpg.outputs.email }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npx lerna@7.3.0 version --conventional-prerelease --preid dev --yes --no-changelog --message "ci: %s"
